#!/bin/bash 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2019.nc 
